# Generated by Django 5.1 on 2024-08-22 03:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskList',
            fields=[
                ('tasklistid', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('taskid', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('importance', models.CharField(choices=[('Alto', 'Alto'), ('Medio', 'Medio'), ('Bajo', 'Bajo')], max_length=20)),
                ('stage', models.CharField(choices=[('En proceso', 'En proceso'), ('Finalizado', 'Finalizado'), ('Sin iniciar', 'Sin iniciar')], max_length=20)),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('tasklistid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.tasklist')),
            ],
        ),
    ]
