# Generated by Django 5.1 on 2024-08-22 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='description',
        ),
        migrations.RemoveField(
            model_name='task',
            name='importance',
        ),
        migrations.RemoveField(
            model_name='task',
            name='stage',
        ),
    ]
